import os
import json
from typing import Dict, Any
from openai import OpenAI
from dotenv import load_dotenv

load_dotenv()

# Unified client for Ollama or Remote API
USE_REMOTE_LLM = os.environ.get("USE_REMOTE_LLM", "false").lower() == "true"

if USE_REMOTE_LLM:
    # Example for using a remote OpenAI-compatible API
    client = OpenAI(
        api_key=os.environ.get("OPENAI_API_KEY", "dummy"),
        base_url=os.environ.get("OPENAI_BASE_URL", "https://api.openai.com/v1")
    )
    MODEL_NAME = os.environ.get("MODEL_NAME", "gpt-3.5-turbo")
else:
    # Local Ollama endpoint
    client = OpenAI(
        api_key="ollama", # required but ignored
        base_url="http://localhost:11434/v1"
    )
    MODEL_NAME = "qwen3.5:4b"

def generate_node(state: Dict[str, Any]) -> Dict[str, Any]:
    """
    Generates a natural prose answer based on the query and retrieved chunks.
    Does NOT format claims or citations.
    """
    query = state["query"]
    chunks = state["chunks"]
    feedback = state.get("feedback", "")
    
    # Format chunks for context
    chunk_text = "\n\n".join([f"--- CHUNK {c['clause_id']} (Spec {c['spec_id']}) ---\n{c['content']}" for c in chunks])
    
    system_prompt = (
        "You are a helpful telecom assistant. Answer the user's query based ONLY on the provided SOURCE CHUNKS. "
        "Answer naturally in plain prose. Do not include citations or brackets like [1] in your answer."
    )
    
    user_prompt = f"<SOURCE CHUNKS>\n{chunk_text}\n</SOURCE CHUNKS>\n\n<QUERY>\n{query}\n</QUERY>"
    
    if feedback:
        user_prompt += f"\n\n<FEEDBACK FROM PREVIOUS ATTEMPT>\n{feedback}\nPlease revise your answer to ensure all claims are strictly supported by the sources.\n</FEEDBACK FROM PREVIOUS ATTEMPT>"

    response = client.chat.completions.create(
        model=MODEL_NAME,
        messages=[
            {"role": "system", "content": system_prompt},
            {"role": "user", "content": user_prompt}
        ],
        temperature=0.3
    )
    answer = response.choices[0].message.content
        
    return {"answer": answer}

def verify_claims_node(state: Dict[str, Any]) -> Dict[str, Any]:
    """
    Acts as a strict judge to ensure every claim in the answer is supported by the chunks.
    Returns JSON containing boolean support and unsupported claims.
    """
    answer = state["answer"]
    chunks = state["chunks"]
    retries = state.get("retries", 0)
    
    chunk_text = "\n\n".join([f"--- CHUNK {c['clause_id']} (Spec {c['spec_id']}) ---\n{c['content']}" for c in chunks])
    
    prompt = f"""You are a strict, impartial fact-checker. You will be provided with an ANSWER generated by an AI assistant, and a set of SOURCE CHUNKS retrieved from 3GPP telecom specifications.

Your task is to verify if every factual claim in the ANSWER is strictly supported by the SOURCE CHUNKS.
Do NOT use outside knowledge. Strict entailment is required. If a claim is not supported, you must fail the verification.

<SOURCE CHUNKS>
{chunk_text}
</SOURCE CHUNKS>

<ANSWER>
{answer}
</ANSWER>

Evaluate the answer step-by-step:
1. Extract the core claims made in the ANSWER.
2. For each claim, check if it is explicitly stated or strictly entailed by the SOURCE CHUNKS.
3. If ANY claim is unsupported or contradicts the chunks, fail the verification.

Provide your output in the following JSON format ONLY:
{{
  "is_supported": boolean,
  "reasoning": "brief explanation of your judgement",
  "unsupported_claims": [
    "list any claims that were not supported by the sources, or leave empty if all are supported"
  ]
}}"""

    response = client.chat.completions.create(
        model=MODEL_NAME,
        messages=[
            {"role": "user", "content": prompt}
        ],
        response_format={"type": "json_object"},
        temperature=0.0
    )
    raw_json = response.choices[0].message.content
    verification = json.loads(raw_json)
            
    is_supported = verification.get("is_supported", False)
    unsupported = verification.get("unsupported_claims", [])
    
    feedback = ""
    if not is_supported and unsupported:
        feedback = "The following claims were NOT supported by the source text and must be removed or corrected:\n- " + "\n- ".join(unsupported)
        
    return {
        "verification_passed": is_supported,
        "feedback": feedback,
        "retries": retries + 1
    }
